export const LOAD_USER_BY_PHOTO = "LOAD_USERS_BY_PHOTO";
export const LOAD_PHOTOS_BY_USER = "LOAD_PHOTOS_BY_USER";
export const LOAD_GROUPS_BY_USERS = "LOAD_GROUPS_BY_USERS";
export const LOAD_COMMENTS_BY_POSTS = "LOAD_COMMENTS_BY_POSTS";
export const LOAD_POSTS_BY_COMMENTS = "LOAD_POSTS_BY_COMMENTS";
export const LOAD_CATEGORY_BY_POSTS = "LOAD_CATEGORY_BY_POSTS";
